export const SET_STUDENTS = "STUDENTS/SET_STUDENTS";
export const FETCH_START = "STUDENTS/FETCH_START";
export const FETCH_END = "STUDENTS/FETCH_END";
export const FETCH_FAILURE = "STUDENTS/FETCH_FAILURE";
export const FETCH_SUCCESS = "STUDENTS/FETCH_SUCCESS";
export const LOGIN_SUCCESS = 'AUTH/SUCCESS';
export const LOGIN_FAILURE = "AUTH/FAILURE";
export const LOGOUT = "AUTH/LOGOUT";
export const ADD_STUDENT = 'STUDENTS/ADD_STUDENTS'

